image:
  file: .gitpod.Dockerfile
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: prebuilt-in-gitpod
vscode:
  extensions:
    - esbenp.prettier-vscode
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - github.copilot
    - ms-azuretools.vscode-docker
